baseURL = 'https://hanamichisakuragiking.github.io/rootready/'
languageCode = 'en-us'
title = 'RootReady'
theme = 'Hextra'

[params]
  description = "From zero to your own server - no sysadmin degree required."

[params.navbar]
  displayTitle = true
  displayLogo = false

[markup.highlight]
  noClasses = false

[[menu.main]]
  identifier = "lessons"
  name = "Lessons"
  pageRef = "/lessons"
  weight = 1

[[menu.main]]
  name = "Search"
  weight = 2
  [menu.main.params]
    type = "search"