baseURL = 'https://hanamichisakuragiking.github.io/rootready/'
languageCode = 'en-us'
title = 'RootReady'
theme = 'Hextra'

[params]
  description = "From zero to your own server - no sysadmin degree required."

[params.navbar]
  displayTitle = true
  displayLogo = false

[markup.highlight]
  noClasses = false